# -*- coding: utf-8 -*-
"""Amazon_Reviews_DC.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vqS6NKE_vNX9QYz7LbjQQG5f8Ty24nQ6
"""

!wget https://mcauleylab.ucsd.edu/public_datasets/data/amazon_2023/raw/review_categories/Electronics.jsonl.gz

!gunzip Electronics.jsonl.gz

"""Now, we will try a stratified random sampling method (stratifiying by rating and helpful vote)"""

import json
from collections import defaultdict

# Adjust this line if your helpful votes column is named differently
helpful_field = 'helpful_vote'  # or 'helpful_votes', as appropriate

strata_counts = defaultdict(int)
total_count = 0

with open('Electronics.jsonl', 'r') as f:
    for line in f:
        record = json.loads(line)
        rating = record.get('rating')
        helpful_votes = record.get(helpful_field, 0)
        helpful_bin = 'helpful' if helpful_votes > 0 else 'not_helpful'
        key = (rating, helpful_bin)
        strata_counts[key] += 1
        total_count += 1

print('Total records:', total_count)
print('Example stratum and count:', list(strata_counts.items())[:5])

sample_size = 20000
strata_targets = {}
for key, count in strata_counts.items():
    # Calculate proportional size, always at least 1 if present
    target = int(round((sample_size / total_count) * count))
    target = max(1, min(target, count))  # don't exceed stratum size
    strata_targets[key] = target

print('Example stratum targets:', list(strata_targets.items())[:5])

import random
strata_samples = defaultdict(list)
strata_seen = defaultdict(int)

with open('Electronics.jsonl', 'r') as f:
    for line in f:
        record = json.loads(line)
        rating = record.get('rating')
        helpful_votes = record.get(helpful_field, 0)
        helpful_bin = 'helpful' if helpful_votes > 0 else 'not_helpful'
        key = (rating, helpful_bin)
        target = strata_targets.get(key, 0)
        if target == 0:
            continue  # skip strata not sampled
        strata_seen[key] += 1
        if len(strata_samples[key]) < target:
            strata_samples[key].append(record)
        else:
            j = random.randint(1, strata_seen[key])
            if j <= target:
                strata_samples[key][j - 1] = record

final_sample = []
for group in strata_samples.values():
    final_sample.extend(group)

print('Final sample size:', len(final_sample))

with open('stratified_sample_20k.jsonl', 'w') as out_file:
    for rec in final_sample:
        out_file.write(json.dumps(rec) + '\n')

"""Finally, we will join it with the metadata database."""

!wget https://mcauleylab.ucsd.edu/public_datasets/data/amazon_2023/raw/meta_categories/meta_Electronics.jsonl.gz

!gunzip meta_Electronics.jsonl.gz

import pandas as pd
sample_df = pd.read_json('stratified_sample_20k.jsonl', lines=True)

parent_asin_list = set(sample_df['parent_asin'])

import json
metadata_fields = [
    'parent_asin', 'main_category', 'title', 'average_rating', 'rating_number',
    'features', 'description', 'price', 'store', 'categories', 'details', 'bought_together'
] # pick only what you need (exclude 'images','videos')

filtered_meta = []
with open('meta_Electronics.jsonl', 'r') as f:
    for line in f:
        meta = json.loads(line)
        if meta.get('parent_asin') in parent_asin_list:
            filtered = {col: meta.get(col, None) for col in metadata_fields}
            filtered_meta.append(filtered)

meta_df_small = pd.DataFrame(filtered_meta)

# Ensure 'parent_asin' is the joining column in both
merged_df = sample_df.merge(meta_df_small, on='parent_asin', how='left')

merged_df.head()

merged_df.to_csv('merged_electronics_sample.csv', index=False)